### ISSUE TITLE
[JENKINS-42910] After update of slave.jar to 3.5 xUnit an Plot plugin no more working

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/remoting#1228]
<p>After update of Jenkins from 2.8 to 2.48 xUnit plugin and also Plot plugin stopped working.<br/>
 This Jenkins update changed version of slave.jar from 2.58 to 3.5.<br/>
Reverting slave.jar back to 2.58 solved issue.Therefore I created this issue for remoting.</p>

<p>Plot Plugin gets stuck. Last log in console:</p>

<pre>
Recording plot data
Saving plot series data from: myFile</pre>
<p>Publishing of xUnit results abort with exception:</p>

<pre>
WARNING: Step ?Publish xUnit test result report? aborted due to exception: 
java.io.IOException: remote file operation failed: /myDir/workspace/myJob at hudson.remoting.Channel@​29a7ac09:escloc22_103: hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
    at hudson.FilePath.act(FilePath.java:992)
    at hudson.FilePath.act(FilePath.java:974)
    at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
    at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
    at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
    at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
    at hudson.model.Build$BuildExecution.post2(Build.java:186)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
    at hudson.model.Run.execute(Run.java:1753)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:405)
Caused by: hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:183)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:44)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
    at hudson.remoting.Request$2.run(Request.java:336)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
    at ......remote call to escloc22_103(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
    at hudson.remoting.Channel.call(Channel.java:830)
    at hudson.FilePath.act(FilePath.java:985)
    ... 14 more
Caused by: org.jenkinsci.plugins.xunit.exception.XUnitException: Conversion error remote file operation failed: /cicp/jenkins/home/userContent/xunit/GoogleTest/1.6 at hudson.remoting.Channel@​6659c656:channel: java.io.IOException: Remote call on channel failed
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convert(XUnitConversionService.java:90)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:146)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:44)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
    at hudson.remoting.Request$2.run(Request.java:336)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.io.IOException: remote file operation failed: /cicp/jenkins/home/userContent/xunit/GoogleTest/1.6 at hudson.remoting.Channel@​6659c656:channel: java.io.IOException: Remote call on channel failed
    at hudson.FilePath.act(FilePath.java:992)
    at hudson.FilePath.act(FilePath.java:974)
    at hudson.FilePath.exists(FilePath.java:1439)
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convertInputMetricXSL(XUnitConversionService.java:105)
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convert(XUnitConversionService.java:79)
    ... 11 more
Caused by: java.io.IOException: Remote call on channel failed
    at hudson.remoting.Channel.call(Channel.java:838)
    at hudson.FilePath.act(FilePath.java:985)
    ... 15 more
Caused by: java.lang.NoClassDefFoundError: hudson/remoting/RemoteClassLoader$RemoteIClassLoader
    at hudson.remoting.RemoteClassLoader.export(RemoteClassLoader.java:721)
    at hudson.remoting.UserRequest.<init>(UserRequest.java:71)
    at hudson.remoting.Channel.call(Channel.java:828)
    ... 16 more</pre>
<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=hjhafner">hjhafner</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-42910" target="_blank">After update of slave.jar to 3.5 xUnit an Plot plugin no more working</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: remoting
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2017-09-02T22:14:21+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-25
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After update of Jenkins from 2.8 to 2.48 xUnit plugin and also Plot plugin stopped working.
 This Jenkins update changed version of slave.jar from 2.58 to 3.5.
Reverting slave.jar back to 2.58 solved issue.Therefore I created this issue for remoting.</p>

<p>Plot Plugin gets stuck. Last log in console:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Recording plot data
Saving plot series data from: myFile</pre>
</div></div>
<p>Publishing of xUnit results abort with exception:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">WARNING: Step ?Publish xUnit test result report? aborted due to exception: 
java.io.IOException: remote file operation failed: /myDir/workspace/myJob at hudson.remoting.Channel@29a7ac09:escloc22_103: hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
    at hudson.FilePath.act(FilePath.java:992)
    at hudson.FilePath.act(FilePath.java:974)
    at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
    at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
    at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
    at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
    at hudson.model.Build$BuildExecution.post2(Build.java:186)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
    at hudson.model.Run.execute(Run.java:1753)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:405)
Caused by: hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:183)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:44)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
    at hudson.remoting.Request$2.run(Request.java:336)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
    at ......remote call to escloc22_103(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
    at hudson.remoting.Channel.call(Channel.java:830)
    at hudson.FilePath.act(FilePath.java:985)
    ... 14 more
Caused by: org.jenkinsci.plugins.xunit.exception.XUnitException: Conversion error remote file operation failed: /cicp/jenkins/home/userContent/xunit/GoogleTest/1.6 at hudson.remoting.Channel@6659c656:channel: java.io.IOException: Remote call on channel failed
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convert(XUnitConversionService.java:90)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:146)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:44)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
    at hudson.remoting.Request$2.run(Request.java:336)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.io.IOException: remote file operation failed: /cicp/jenkins/home/userContent/xunit/GoogleTest/1.6 at hudson.remoting.Channel@6659c656:channel: java.io.IOException: Remote call on channel failed
    at hudson.FilePath.act(FilePath.java:992)
    at hudson.FilePath.act(FilePath.java:974)
    at hudson.FilePath.exists(FilePath.java:1439)
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convertInputMetricXSL(XUnitConversionService.java:105)
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convert(XUnitConversionService.java:79)
    ... 11 more
Caused by: java.io.IOException: Remote call on channel failed
    at hudson.remoting.Channel.call(Channel.java:838)
    at hudson.FilePath.act(FilePath.java:985)
    ... 15 more
Caused by: java.lang.NoClassDefFoundError: hudson/remoting/RemoteClassLoader$RemoteIClassLoader
    at hudson.remoting.RemoteClassLoader.export(RemoteClassLoader.java:721)
    at hudson.remoting.UserRequest.&lt;init&gt;(UserRequest.java:71)
    at hudson.remoting.Channel.call(Channel.java:828)
    ... 16 more</pre>
</div></div>
<p> </p>

<p> </p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.48<br/>
xUnit plugin 1.102<br/>
JUnit Plugin 1.20<br/>
Plot Plugin 1.9<br/>
RHEL6.3, Java 1.8.0_92
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/oleg_nenashev.png" title="oleg_nenashev's avatar" /> oleg_nenashev:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-42910?focusedId=293300&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-293300">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I doubt it is a regression inside Remoting. There are similar issues reported to previous versions, e.g. <a href="https://issues.jenkins.io/browse/JENKINS-32403" title="xUnit NoClassDefFoundError when converting CTest output on Windows slave" class="issue-link" data-issue-key="JENKINS-32403"><del>JENKINS-32403</del></a>. <a href="https://issues.jenkins.io/browse/JENKINS-39880" title="Jenkins agents should offer better Diagnostics remote operation failures due to JDK-8017777" class="issue-link" data-issue-key="JENKINS-39880"><del>JENKINS-39880</del></a> says it is probably a JVM issue in some cases</p>
</pre>
</details>

</ul>
</details>

<p>I doubt it is a regression inside Remoting. There are similar issues reported to previous versions, e.g. <a href="https://issues.jenkins.io/browse/JENKINS-32403" title="xUnit NoClassDefFoundError when converting CTest output on Windows slave" class="issue-link" data-issue-key="JENKINS-32403"><del>JENKINS-32403</del></a>. <a href="https://issues.jenkins.io/browse/JENKINS-39880" title="Jenkins agents should offer better Diagnostics remote operation failures due to JDK-8017777" class="issue-link" data-issue-key="JENKINS-39880"><del>JENKINS-39880</del></a> says it is probably a JVM issue in some cases</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/oleg_nenashev.png" title="oleg_nenashev's avatar" /> oleg_nenashev:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-42910?focusedId=312532&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-312532">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>No respons from the reporter. Closing as a duplicate</p>
</pre>
</details>

</ul>
</details>

<p>No respons from the reporter. Closing as a duplicate</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a href="https://github.com/jenkinsci/remoting/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-39880%22">JENKINS-39880</a>]</i>
